[package]
name = "study-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.11"
notify = { version = "5.1.0", default-features = false, features = ["serde"] }
reqwest = { version = "0.11.14", features = ["multipart", "json", "serde_json"], default-features = false }
tokio = { version = "1.26.0", features = ["full"] }
tokio-rusqlite = "0.3.0"
