[package]
name = "study-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
axum = "0.6.11"
clap = { version = "4.1.11", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
env_logger = "0.10.0"
futures = "0.3.27"
log = { version = "0.4.17", features = ["serde"] }
notify = { version = "5.1.0", default-features = false, features = ["serde"] }
reqwest = { version = "0.11.14", features = ["multipart", "json", "serde_json"], default-features = false }
rusqlite = "0.28.0"
serde = "1.0.158"
tokio = { version = "1.26.0", features = ["full"] }
tokio-rusqlite = "0.3.0"
